### ISSUE TITLE
Stuck on decoding. Running using Wav2Letter Docker Container

### ISSUE THREAD

**Issue by Juanvulcano** [mailong25/vietnamese-speech-recognition#2]
![Screen Shot 2020-08-28 at 11 36 19 AM](https://user-images.githubusercontent.com/9177978/91559445-675fe680-e938-11ea-8512-2afb45172ba7.png)

Hi, I tried both CPU and GPU versions but it fails. Any idea what could be happening? 

Best wishes :)

**Comment by mailong25** [comment]
You should follow the exact steps at:
https://github.com/mailong25/vietnamese-speech-recognition/blob/master/dependencies.md
