### ISSUE TITLE
Model Performance

### ISSUE THREAD

**Issue by buimanhlinh96** [mailong25/vietnamese-speech-recognition#4]
Em chào anh Long,
Trước tiên em xin cảm ơn về sự đóng góp của anh cho cộng đồng NLP Việt Nam.
Em có 1 câu hỏi, khi dev repo này xuống dưới những con chip nhỏ ví dụ như ARM cortext thì tốc độ inference có tốt không ạ so với phương pháp truyền thống như MFCC+HMM. Em đang trong quá trình lựa chọn model tuy nhiên lại chưa có điều kiện dev xuống để test thử.
Em cảm ơn anh ạ!

**Comment by mailong25** [comment]
Tốc độ sẽ chậm hơn MFCC+HMM nhiều vì chi phí tính toán ở bước feature extraction (wav2vec) khá cao
