### ISSUE TITLE
Cập nhật cho wav2letter v0.2?

### ISSUE THREAD

**Issue by trahoa** [mailong25/vietnamese-speech-recognition#5]
Theo mình hiểu thì code từ đây `https://github.com/mailong25/wav2letter.git` đang chưa support run/train sử dụng GPU. Long có thể update code lên wav2letter v0.2 stable hiện tại `https://github.com/facebookresearch/wav2letter/tree/v0.2` được không?

Hiện tại mình build cả flashlight và wav2letter v0.2 thì mô hình wav2vec load ổn, các file temp xuất ra đều đúng, nhưng đến bước chạy Decoder của wav2letter thì chương trình dừng lại (có bug nhỏ về đổi biến silweight thành silscore thì mình đã sửa).

Cảm ơn,

**Comment by ThanhBarTN** [comment]
> Theo mình hiểu thì code từ đây `https://github.com/mailong25/wav2letter.git` đang chưa support run/train sử dụng GPU. Long có thể update code lên wav2letter v0.2 stable hiện tại `https://github.com/facebookresearch/wav2letter/tree/v0.2` được không?
> 
> Hiện tại mình build cả flashlight và wav2letter v0.2 thì mô hình wav2vec load ổn, các file temp xuất ra đều đúng, nhưng đến bước chạy Decoder của wav2letter thì chương trình dừng lại (có bug nhỏ về đổi biến silweight thành silscore thì mình đã sửa).
> 
> Cảm ơn,

Looking forward to answering from Mr.Long to you

**Comment by mailong25** [comment]
For training/inference with GPU. Please redo the installation steps with GPU version as follow:
https://github.com/mailong25/vietnamese-speech-recognition/blob/master/dependencies.md

I'm planning to move the project to wav2vec 2.0 without the dependence on wav2letter.

**Comment by ThanhBarTN** [comment]
> For training/inference with GPU. Please redo the installation steps with GPU version as follow:
> https://github.com/mailong25/vietnamese-speech-recognition/blob/master/dependencies.md
> 
> I'm planning to move the project to wav2vec 2.0 without the dependence on wav2letter.

Thanks for your reply. I hope wav2vec project will be available soon. Sincerely
Một lần nữa cảm ơn anh ạ 💯

**Comment by trahoa** [comment]
> For training/inference with GPU. Please redo the installation steps with GPU version as follow:
> https://github.com/mailong25/vietnamese-speech-recognition/blob/master/dependencies.md
> 
> I'm planning to move the project to wav2vec 2.0 without the dependence on wav2letter.

Thank you very much!!!

Just wondering how do you plan to use wav2vec 2.0 without wav2letter? Since wav2vec 2.0 needs python binding of wav2letter (https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md) to work with a language model.

**Comment by ThanhBarTN** [comment]
@mailong25 Hi will you check this command please. I ran this after had run all command before this command
cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CUDA=ON

![image](https://user-images.githubusercontent.com/36233920/98099845-a7a48d80-1ec2-11eb-954a-e95617e9d11d.png)

**Comment by trahoa** [comment]
> @mailong25 Hi will you check this command please. I ran this after had run all command before this command
> cmake .. -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CUDA=ON
> 
> ![image](https://user-images.githubusercontent.com/36233920/98099845-a7a48d80-1ec2-11eb-954a-e95617e9d11d.png)

The reason of this error is your cmake (it's toooo old). Update cmake and the error will be gone!
