### ISSUE TITLE
How did you create lst file for train and test

### ISSUE THREAD

**Issue by ThanhBarTN** [mailong25/vietnamese-speech-recognition#6]
Hi Mr @mailong25,
I'm having issue in generate train and test files. I see in your code that you're using 2 files which has lst extensions. But with my own datasets (for example: VLSP2020), I create my own train and test file and training process seems to work fine until this happened
![image](https://user-images.githubusercontent.com/36233920/98646664-410dec80-2366-11eb-892a-6844049ffc2e.png)
Can you explain this. Thank you so much. Below are my 2 files
[test.txt](https://github.com/mailong25/vietnamese-speech-recognition/files/5515729/test.txt)
[train.txt](https://github.com/mailong25/vietnamese-speech-recognition/files/5515730/train.txt)

**Comment by mailong25** [comment]
For all the paths listed in the lst file, check if the corresponding h5context existed. Also, make sure all the h5context files are created properly. 
Please refer to this https://github.com/facebookresearch/wav2letter/issues/436#issuecomment-655622793

**Comment by ThanhBarTN** [comment]
> For all the paths listed in the lst file, check if the corresponding h5context existed. Also, make sure all the h5context files are created properly.
> Please refer to this [facebookresearch/wav2letter#436 (comment)](https://github.com/facebookresearch/wav2letter/issues/436#issuecomment-655622793)

How can I find h5context files even with your audio data in your code?

**Comment by ThanhBarTN** [comment]
> For all the paths listed in the lst file, check if the corresponding h5context existed. Also, make sure all the h5context files are created properly.
> Please refer to this [facebookresearch/wav2letter#436 (comment)](https://github.com/facebookresearch/wav2letter/issues/436#issuecomment-655622793)

Thanks sir, I'll check and ask for your help if any things happen
